AllCops:
  TargetRubyVersion: 3.1
  UseCache: true
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - lib/grape-oas.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
