plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  UseCache: true
  NewCops: enable
  SuggestExtensions: false
  Include:
    - "**/*.rb"
    - "**/*.gemspec"
    - "**/Gemfile"
    - "**/Rakefile"

Naming/FileName:
  Exclude:
    - lib/grape-oas.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 60
  Exclude:
    - lib/grape_oas/introspectors/dry_introspector.rb

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Max: 70
  Exclude:
    - lib/grape_oas/api_model_builders/dry_introspector.rb
    - lib/grape_oas/introspectors/dry_introspector.rb
    - test/**/*

Metrics/CyclomaticComplexity:
  Max: 40
  Exclude:
    - lib/grape_oas/api_model_builders/dry_introspector.rb
    - lib/grape_oas/introspectors/entity_introspector.rb
    - lib/grape_oas/introspectors/dry_introspector.rb
    - test/**/*

Metrics/PerceivedComplexity:
  Max: 40
  Exclude:
    - lib/grape_oas/api_model_builders/dry_introspector.rb
    - lib/grape_oas/introspectors/entity_introspector.rb
    - lib/grape_oas/introspectors/dry_introspector.rb
    - test/**/*

Metrics/BlockLength:
  Max: 60
  Exclude:
    - test/**/*
    - Rakefile

Metrics/ParameterLists:
  Max: 13

Style/OpenStructUse:
  Exclude:
    - test/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*

Style/SafeNavigationChainLength:
  Max: 4

Naming/PredicateMethod:
  AllowedMethods:
    - validate!

Layout/LineLength:
  Max: 140

Style/MultilineBlockChain:
  Exclude:
    - lib/grape_oas/exporter/oas3_schema.rb

Lint/StructNewOverride:
  Exclude:
    - test/**/*

Lint/DuplicateBranch:
  Exclude:
    - lib/grape_oas/introspectors/dry_introspector.rb
    - lib/grape_oas/introspectors/entity_introspector.rb

Naming/VariableNumber:
  Exclude:
    - test/**/*

Minitest/MultipleAssertions:
  Enabled: false
